###  get movies
GET http://localhost:3000/movies

### get movies by id
GET http://localhost:3000/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### get movies by genre
GET http://localhost:3000/movies?genre=Drama

### create a movie with POST
POST http://localhost:3000/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users", 
  "title": "The Godfather",
  "year": 1970,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "rate":8.3,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime"
  ]
}

# in the json above 'sql' is ignored because is not contemplated in the schema
# invalid input
# {
#   "title": 1,
#   "year": "p"
# }

### update movie
PATCH http://localhost:3000/movies/1dccbc9c8524710e
Content-Type: application/json

{
  "year": 2000
}

### delete movie
DELETE http://localhost:3000/movies/ed557e5d0d7eee65

